spring:
  websocket:
    endpoint: /ws
    allowed-origins:
      - https://secret-fe.vercel.app
      - https://quizzle.p-e.kr

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: false

logging:
  level:
    com.ll.quizzle: TRACE
    com.ll.quizzle.global.security.oauth2: TRACE
    com.ll.quizzle.global.jwt: TRACE
    org.springframework.security: DEBUG
    org.springframework.web.socket: DEBUG


server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  error:
    include-stacktrace: never
    include-message: never
    whitelabel:
      enabled: false

custom:
  site:
    cookieDomain: quizzle.p-e.kr
    frontUrl: "https://secret-fe.vercel.app"
    backUrl: "https://quizzle.p-e.kr"
    name: Quizzle
  cors:
    allowed-origins:
      - https://secret-fe.vercel.app
      - https://quizzle.p-e.kr

app:
  websocket:
    use-distributed-sessions: true
